### ISSUE TITLE
Test additional renovate regex manager to read YAML 

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/packages#1073]
- [ ] Test updated `package.yaml`:

  ```yaml
  #...
  version:
    latest: 1.2.3
    renovate:
      source: github-releases 
      name: owner/repo
  #...
  ```

- [ ] Migrate to new regex manager
