### ISSUE TITLE
Create tool definitions in YAML

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/packages#25]
- [x] Create example
- [x] ~Create schema for tool definition~ (unable to find tool for validation of YAML/JSON)
- [x] Create tool definition `tool.yaml` for every tool
- [x] Create `README.md` for every tool

    ```
    yq read --tojson docker/tool.yaml | \
        jq --raw-output '
            "# \(.name)\n\n\(.description)\n\n[GitHub](https://github.com/\(.repo))\n"
        '
    yq read --tojson act/tool.yaml | \
        jq --raw-output '
            select(.links != null) | 
            .links[] | 
            "\n[\(.text)](\(.url))\n"
        '
    ```

**Comment by nicholasdille** [comment]
Example:

```yaml
name: docker
description: Docker Community Edition
repo: docker/docker-ce
links:
- text: Homepage
  url: https://www.docker.com/
tags:
- docker
- container
```
